---
# tasks file for vector-role
- name: Get vector distrib | CentOS
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
    dest: "./vector-{{ vector_version }}-1.x86_64.rpm"
  when: ansible_distribution == "CentOS"
# - name: Install vector packages | CentOS
#   become: true
#   ansible.builtin.yum:
#     name:
#       - "vector-{{ vector_version }}-1.x86_64.rpm"
#   when: ansible_distribution == "CentOS"
- name: Get vector distrib | Ubuntu
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector_{{ vector_version }}-1_amd64.deb"
    dest: "./vector-{{ vector_version }}-1_amd64.deb"
  when: ansible_distribution == "Ubuntu"
- name: Install vector packages | Ubuntu
  become: true
  ansible.builtin.apt:
    deb: "./vector-{{ vector_version }}-1_amd64.deb"
  when: ansible_distribution == "Ubuntu"
