---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: centos7
    image: quay.io/centos/centos:7
    # image: registry.access.redhat.com/ubi8/ubi-init
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
    - destroy
    - create
    - converge
    - destroy


